apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: java-to-eks
  namespace: accelerator-system
spec:
  git:
    ref:
      branch: eks
    url: https://github.com/mhoshi-vm/sb-labs-demo
