apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tap-labs-demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=labs'
spec:
  type: service
  lifecycle: unknown
  owner: guests