apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: CHANGEME
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
  name: CHANGEME
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
  params:
    - name: gitops_ssh_secret
      value: git-ssh
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: mhoshi-vm
    - name: gitops_repository_name
      value: GITREPO
  source:
    git:
      ref:
        branch: main
      url: https://github.com/mhoshi-vm/GITREPO.git
